-- ============================================================================
-- BLACKBOX V1 DATABASE SCHEMA
-- ============================================================================
-- Generated: 2026-01-01
-- Database: Supabase (PostgreSQL)
-- Purpose: Complete schema documentation for BLACKBOX V1
-- ============================================================================

-- ============================================================================
-- TABLE: profiles (ACTIVE - PRIMARY USER TABLE)
-- ============================================================================
-- Purpose: Core user profile data, populated during onboarding
-- RLS: REQUIRED - user_id based policies
-- Status: ACTIVELY USED
-- ============================================================================

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  
  -- Onboarding capture fields (Step 1: Context)
  context text,
  artist_name text,
  
  -- Onboarding capture fields (Step 2: Direction)
  primary_goal text,
  genre_sound text,
  career_stage text,
  
  -- Onboarding capture fields (Step 3: Patterns)
  strengths text,
  weaknesses text,
  constraints text,
  current_focus text,
  
  -- Onboarding state tracking
  onboarding_completed boolean NOT NULL DEFAULT false,
  onboarding_completed_at timestamp with time zone,
  
  -- Legacy/redundant fields (NOT USED in current code)
  genre text,              -- REDUNDANT: use genre_sound instead
  release_phase text,      -- UNUSED: phase tracking not implemented yet
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_email_key UNIQUE (email),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- ============================================================================
-- RLS POLICIES FOR profiles
-- ============================================================================
-- CRITICAL: These policies MUST be enabled for multi-tenant security

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read their own profile
CREATE POLICY "Users can view own profile"
  ON public.profiles
  FOR SELECT
  USING (auth.uid() = id);

-- Policy: Users can insert their own profile
CREATE POLICY "Users can insert own profile"
  ON public.profiles
  FOR INSERT
  WITH CHECK (auth.uid() = id);

-- Policy: Users can update their own profile
CREATE POLICY "Users can update own profile"
  ON public.profiles
  FOR UPDATE
  USING (auth.uid() = id);

-- ============================================================================
-- TABLE: tasks (ACTIVE - TASK MANAGEMENT)
-- ============================================================================
-- Purpose: User tasks (generated by system or user-created)
-- RLS: REQUIRED - user_id based policies
-- Status: ACTIVELY USED
-- ============================================================================

CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  
  -- Task identification
  task_name text NOT NULL,
  title text,              -- REDUNDANT with task_name (cleanup needed)
  
  -- Task metadata
  kind text DEFAULT 'user',           -- 'today', 'user', 'release', etc.
  source text DEFAULT 'user',         -- 'system', 'user', 'n8n', etc.
  priority integer DEFAULT 3,         -- 1 (high) to 5 (low)
  
  -- Task lifecycle
  status text DEFAULT 'pending',      -- 'pending', 'completed', 'skipped'
  
  -- Task context (some fields unused in V1)
  purpose text,                       -- UNUSED: why this task exists
  guardrail text,                     -- UNUSED: constraint/limitation
  suggestion text,                    -- UNUSED: recommended approach
  
  -- Release association (for future release task flows)
  release_id uuid,
  phase text,                         -- UNUSED: 'pre-release', 'release', 'post-release'
  due_date date,                      -- UNUSED: not enforced in V1
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT tasks_release_id_fkey FOREIGN KEY (release_id) REFERENCES public.releases(id) ON DELETE SET NULL,
  CONSTRAINT tasks_status_check CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'skipped'::text])),
  CONSTRAINT tasks_phase_check CHECK (phase = ANY (ARRAY['pre-release'::text, 'release'::text, 'post-release'::text]))
);

-- ============================================================================
-- RLS POLICIES FOR tasks
-- ============================================================================

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own tasks
CREATE POLICY "Users can view own tasks"
  ON public.tasks
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own tasks
CREATE POLICY "Users can insert own tasks"
  ON public.tasks
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own tasks
CREATE POLICY "Users can update own tasks"
  ON public.tasks
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy: Users can delete their own tasks
CREATE POLICY "Users can delete own tasks"
  ON public.tasks
  FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- TABLE: releases (DEFINED BUT NOT ACTIVELY USED IN V1)
-- ============================================================================
-- Purpose: Track artist releases (future V1+ feature)
-- RLS: REQUIRED when activated
-- Status: SCHEMA EXISTS, NOT WIRED TO UI YET
-- ============================================================================

CREATE TABLE public.releases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  
  -- Release details
  title text NOT NULL,
  release_date date,
  release_type text,       -- 'single', 'EP', 'experimental'
  
  -- Release strategy
  goal text,               -- 'growth', 'validation', 'catalog'
  platform_focus text,     -- Which platform to prioritize
  why_it_matters text NOT NULL,
  
  -- Release lifecycle
  status text DEFAULT 'planning',  -- 'planning', 'active', 'completed', 'reflected'
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT releases_pkey PRIMARY KEY (id),
  CONSTRAINT releases_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT releases_type_check CHECK (release_type = ANY (ARRAY['single'::text, 'EP'::text, 'experimental'::text])),
  CONSTRAINT releases_goal_check CHECK (goal = ANY (ARRAY['growth'::text, 'validation'::text, 'catalog'::text])),
  CONSTRAINT releases_status_check CHECK (status = ANY (ARRAY['planning'::text, 'active'::text, 'completed'::text, 'reflected'::text]))
);

-- ============================================================================
-- RLS POLICIES FOR releases (TO BE ENABLED WHEN FEATURE IS ACTIVATED)
-- ============================================================================

ALTER TABLE public.releases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own releases"
  ON public.releases
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own releases"
  ON public.releases
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own releases"
  ON public.releases
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own releases"
  ON public.releases
  FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- TABLE: reflections (DEFINED BUT NOT ACTIVELY USED IN V1)
-- ============================================================================
-- Purpose: Post-release reflection capture (future V1+ feature)
-- RLS: REQUIRED when activated
-- Status: SCHEMA EXISTS, NOT WIRED TO UI YET
-- ============================================================================

CREATE TABLE public.reflections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  release_id uuid,
  
  -- Reflection questions
  achieved_goal boolean,
  what_worked text,
  what_underperformed text,
  do_differently text,
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT reflections_pkey PRIMARY KEY (id),
  CONSTRAINT reflections_release_id_key UNIQUE (release_id),
  CONSTRAINT reflections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT reflections_release_id_fkey FOREIGN KEY (release_id) REFERENCES public.releases(id) ON DELETE CASCADE
);

-- ============================================================================
-- RLS POLICIES FOR reflections (TO BE ENABLED WHEN FEATURE IS ACTIVATED)
-- ============================================================================

ALTER TABLE public.reflections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reflections"
  ON public.reflections
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own reflections"
  ON public.reflections
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own reflections"
  ON public.reflections
  FOR UPDATE
  USING (auth.uid() = user_id);

-- ============================================================================
-- TABLE: artist_context (LEGACY - NOT USED)
-- ============================================================================
-- Purpose: Legacy table from earlier schema iteration
-- Status: REDUNDANT with profiles table, SHOULD BE DEPRECATED
-- Action: Consider dropping this table in next migration
-- ============================================================================

CREATE TABLE public.artist_context (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  
  -- Fields duplicated in profiles table
  primary_goal text,
  genre text,
  career_stage text,
  strengths text,
  weaknesses text,
  constraints text,
  current_focus text,
  
  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  
  CONSTRAINT artist_context_pkey PRIMARY KEY (id),
  CONSTRAINT artist_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

-- Note: This table is not referenced in any application code
-- Recommendation: DROP TABLE in cleanup migration

-- ============================================================================
-- INDEXES (RECOMMENDED FOR PERFORMANCE)
-- ============================================================================

-- Profiles table
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_onboarding_completed ON public.profiles(onboarding_completed);

-- Tasks table
CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_kind ON public.tasks(kind);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status ON public.tasks(user_id, status);

-- Releases table (for future use)
CREATE INDEX IF NOT EXISTS idx_releases_user_id ON public.releases(user_id);
CREATE INDEX IF NOT EXISTS idx_releases_status ON public.releases(status);

-- Reflections table (for future use)
CREATE INDEX IF NOT EXISTS idx_reflections_user_id ON public.reflections(user_id);
CREATE INDEX IF NOT EXISTS idx_reflections_release_id ON public.reflections(release_id);

-- ============================================================================
-- CLEANUP RECOMMENDATIONS
-- ============================================================================
-- The following schema cleanup is recommended for V1.1:
--
-- 1. DROP TABLE artist_context (redundant)
-- 2. Remove unused fields from profiles:
--    - genre (use genre_sound)
--    - release_phase (not implemented)
-- 3. Consolidate task fields:
--    - Remove either task_name or title (keep task_name)
-- 4. Add NOT NULL constraints where appropriate after data validation
-- 5. Consider adding check constraints for career_stage enum values
--
-- ============================================================================

-- ============================================================================
-- CURRENT V1 DATA FLOW
-- ============================================================================
--
-- ONBOARDING FLOW:
-- 1. User signs up → auth.users row created
-- 2. Onboarding starts → profiles row created with id = auth.users.id
-- 3. Step 1 → upserts context, artist_name
-- 4. Step 2 → upserts primary_goal, genre_sound, career_stage
-- 5. Step 3 → upserts strengths, weaknesses, constraints, current_focus
--            + sets onboarding_completed = true
-- 6. Dashboard loads → reads profile, generates Mirror interpretation
--
-- TASK FLOW:
-- 1. Dashboard loads → checks for pending "today" task
-- 2. If none exists → generates task based on current_focus keywords
-- 3. User completes/skips → updates task.status
-- 4. Next dashboard load → generates new task if none pending
--
-- FUTURE FLOWS (Not V1):
-- - Release creation → populates releases table
-- - Release tasks → tasks.release_id links to releases
-- - Post-release → reflections table populated
-- - Pattern learning → reflections feed back into profile interpretation
--
-- ============================================================================
